version: '3.8'
services:
  backend:
    image: projektazurerejestr.azurecr.io/backend:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

  frontend:
    image: projektazurerejestr.azurecr.io/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend